# Initial state of the FSM
initial_state: "LANE_FOLLOWING"

events: #Maps from subscribing topic to signal ids
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True
  intersection_go:
    topic: "simple_coordinator_node/intersection_go"
    msg_type: "BoolStamped"
    trigger: True
  intersection_done:
    topic: "open_loop_intersection_control_node/intersection_done"
    msg_type: "BoolStamped"
    trigger: True
  turn_around:
    topic: "obstacle_safety_node/turn_around"
    msg_type: "BoolStamped"
    trigger: True
  done_turn_around:
    topic: "obstacle_safety_node/turn_around"
    msg_type: "BoolStamped"
    trigger: False
  go_around:
    topic: "obstacle_safety_node/go_around"
    msg_type: "BoolStamped"
    trigger: True
  go_around_done:
    topic: "obstacle_safety_node/go_around"
    msg_type: "BoolStamped"
    trigger: False

# Define global transitions. Available from all states.
global_transitions:
  joystick_override_on: "JOYSTICK_CONTROL"
  parallel_autonomy_on: "PARALLEL_AUTONOMY"
  parallel_autonomy_off: "JOYSTICK_CONTROL"

# Define nodes 
nodes:
  decoder_node: "decoder_node/switch"
# anti_instagram_node: "anti_instagram/switch"
#  apriltag_node: "apriltag_detector_node/switch"
#  vehicle_detector_node: "vehicle_detection_node/switch"
#  led_detector_node: "LED_detector_node/switch"
#  led_emitter_node: "led_emitter_node/switch"
#  static_object_detector_node: "static_object_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  framerate_high: "camera_node/framerate_high_switch"

# Define state transitions
states:
  LANE_FOLLOWING:
    transitions:
      at_stop_line: "INTERSECTION_CONTROL"
      go_around: "GO_AROUND"
      turn_around: "TURN_AROUND"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - stop_line_filter_node
  INTERSECTION_CONTROL:
    transitions:
      intersection_done: "LANE_FOLLOWING"
    active_nodes:
      - line_detector_node
      - lane_filter_node
      - decoder_node
  TURN_AROUND:
    transitions:
      turn_around_done: "LANE_FOLLOWING"
    active_nodes:
      - decoder_node
  GO_AROUND:
    transistions:
      go_around_done: "LANE_FOLLOWING"
    active_nodes:
      - decoder_node
